language: python
python:
  - 3.6
  - 3.7

install:
  - pip install -U pip
  - pip install --progress-bar off tifffile==2019.7.26
  - pip install --progress-bar off git+https://github.com/chunglabmit/mp_shared_memory.git#egg=mp_shared_memory
  - pip install --progress-bar off git+https://github.com/chunglabmit/blockfs.git#egg=blockfs
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off nose

script:
  - pip install .
  - nosetests tests
  - precomputed-tif --help
  - precomputed-webserver --help